#!/usr/bin/env bash

# fail on error
set -eo pipefail

# make sure we are in the git root directory
pushd $(git rev-parse --show-toplevel) >/dev/null

# enforce formatting with Black
poetry run black --quiet --line-length 100 --skip-string-normalization .

# make sure there are no duplicate Berror codes (Bxxxxx codes to help ID points in the code)
export DUP_BERROR_CODES=$(git ls-files '*.py' '*.dart' |while read -r F; do if [ ! -L "$F" ]; then grep -o --no-filename 'B[0-9][0-9][0-9][0-9][0-9] ' "$F"; fi; done |sort |uniq --repeated)
if [ -n "$DUP_BERROR_CODES" ]; then echo "Please remove duplicate Berror code(s): $DUP_BERROR_CODES" |tr -d '\n'; echo; sleep 2; exit 1; fi

# return to former directory
popd >/dev/null

