#!/bin/bash
# cSpell:disable  # don't spell check this file

set -e # exit script if anything fails

usage() {
  echo "Usage:"
  echo "  $0 install YOUR_HUB_DOMAIN YOUR_HUB_IP"
  echo "  $0 upgrade"
}

mode="${1:-}"
case "$mode" in
  install)
    [ $# -eq 3 ] || { usage >&2; exit 1; }
    domain="$2"
    ip="$3"
    ;;
  upgrade)
    [ $# -eq 1 ] || { usage >&2; exit 1; }
    domain=""
    ip=""
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac

## verify $SUDO_USER
test "x$SUDO_USER" != "x" || (echo "Run this script as a normal user using 'sudo'."; false)
test "x$SUDO_USER" != "xroot" || (echo "Run this script as a normal user using 'sudo'."; false)
SUDO_USER_HOME=$(eval echo "~$SUDO_USER")

## install dependencies
sudo apt update
sudo apt install -y wget ansible

## create Ansible script that does most of the installing
mkdir -p "$SUDO_USER_HOME/hub/"
cat <<"_EOF3703_" >"$SUDO_USER_HOME/hub/install.yaml"
---
- hosts: localhost
  become: true
  tasks:

  - name: Run apt upgrade
    apt:
      upgrade: "yes"  # quotes avoid https://github.com/ansible/ansible/issues/56788
      update_cache: true
      cache_valid_time: 432000  # ≥5 days

  - name: Install package dependencies
    # debugging: df --si /  # check in container *and* on host
    apt:
      name:
      - unattended-upgrades
      - python3-poetry  # to install BitBurrow
      - wireguard-tools
      - sqlite3
      - bind9-dnsutils  # `dig` tool
      # 'acl' avoids Ansible temp file permissions issue in 'Install bbhub 🦶1--git clone'
      # (note that creating /home/bitburrow/.ansible/tmp doesn't help; we need package 'acl')
      - acl
      state: latest

  - name: Define poetry path
    set_fact:
      poetry: /usr/bin/poetry
    changed_when: false

  - name: Enable automatic security updates
    # requires package unattended-upgrades
    # see also https://help.ubuntu.com/community/AutomaticSecurityUpdates
    copy:
      content: |
        APT::Periodic::Update-Package-Lists "1";
        APT::Periodic::Unattended-Upgrade "1";
        APT::Periodic::Download-Upgradeable-Packages "1";
        APT::Periodic::AutocleanInterval "7";
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      mode: '0644'

  - name: Allow sudo without password for specific commands
    copy:
      content: |
        bitburrow  ALL = NOPASSWD: /usr/bin/wg *
        bitburrow  ALL = NOPASSWD: /usr/bin/ip *
        bitburrow  ALL = NOPASSWD: /usr/bin/sysctl *
        bitburrow  ALL = NOPASSWD: /usr/bin/iptables *
        bitburrow  ALL = NOPASSWD: /usr/sbin/wg *
        bitburrow  ALL = NOPASSWD: /usr/sbin/ip *
        bitburrow  ALL = NOPASSWD: /usr/sbin/sysctl *
        bitburrow  ALL = NOPASSWD: /usr/sbin/iptables *
        bitburrow  ALL = NOPASSWD: /bin/wg *
        bitburrow  ALL = NOPASSWD: /bin/ip *
        bitburrow  ALL = NOPASSWD: /bin/sysctl *
        bitburrow  ALL = NOPASSWD: /bin/iptables *
        bitburrow  ALL = NOPASSWD: /sbin/wg *
        bitburrow  ALL = NOPASSWD: /sbin/ip *
        bitburrow  ALL = NOPASSWD: /sbin/sysctl *
        bitburrow  ALL = NOPASSWD: /sbin/iptables *
      dest: /etc/sudoers.d/bitburrow
      mode: '0640'

  - name: Add BitBurrow hub user
    user:
      name: bitburrow
      password: '!'  # disabled
      state: present
      create_home: true
      shell: /bin/bash

  - name: Install bbhub 🦶1--git clone
    git:
      repo: https://github.com/BitBurrow/BitBurrow.git
      dest: /home/bitburrow/bitburrow/
      version: main
      update: true
      depth: 1
    become_user: bitburrow
    register: git_result

  - name: Install bbhub 🦶2--configure Poetry so we can find .../bin/bbhub
    command:
      cmd: "{{ poetry }} config virtualenvs.in-project true"
    become_user: bitburrow
    changed_when: false
    when: git_result.changed

  - name: Install bbhub 🦶3--install
    shell: |-
      cd /home/bitburrow/bitburrow/
      {{ poetry }} install
    become_user: bitburrow
    when: git_result.changed

  - name: Install bbhub 🦶4--install headless Chromium for Robot Framework Browser
    shell: |-
      cd /home/bitburrow/bitburrow/
      {{ poetry }} run rfbrowser install chromium-headless-shell  # harmless to rerun
    become_user: bitburrow

  - name: Define bbhub path
    set_fact:
      bbhub: /home/bitburrow/bitburrow/.venv/bin/bbhub
    changed_when: false

  - name: Create config file with given domain, ip
    command:
      cmd: "{{ bbhub }} generate-config {{ domain }} {{ ip }}"
    become_user: bitburrow
    when: domain is defined

  - name: Create systemd service file
    copy:
      content: |
        [Unit]
        Description=BitBurrow
        Documentation=https://bitburrow.com
        After=network.target network-online.target
        #
        [Service]
        Type=exec
        RestartSec=2s
        User=bitburrow
        Group=bitburrow
        WorkingDirectory=/home/bitburrow/bitburrow
        ExecStart={{ poetry }} run python3 {{ bbhub }} serve
        Restart=always
        PrivateTmp=true
        PrivateDevices=false
        NoNewPrivileges=false
        #
        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/bitburrow.service
      mode: '0660'

  - name: Enable systemd service file
    # debugging: sudo systemctl status bitburrow
    # debugging: sudo journalctl -u bitburrow
    systemd:
      name: bitburrow
      enabled: yes
      state: started
      masked: false

  - name: Install BIND 🦶1--install
    apt:
      name:
      - bind9
      state: latest
    when: domain is defined

  - name: Install BIND 🦶2--options file
    # changes from default BIND named.conf.options file:
    # * remove comments, blank lines
    # * disable recursive resolver--add line: recursion no;
    # * disable version, hostname, etc. (`dig @[server ip] hostname.bind TXT CHAOS`)
    copy:
      content: |
        options {
            directory "/var/cache/bind";
            dnssec-validation auto;
            listen-on-v6 { any; };
            recursion no;
            version none;
            hostname none;
            server-id none;
        };
      dest: /etc/bind/named.conf.options
    register: bind_options
    when: domain is defined

  - name: Install BIND 🦶3--add zone config
    blockinfile:
      block: |
        zone "{{ domain }}" {
          type master;
          file "/var/cache/bind/db.{{ domain }}";
          allow-transfer { none; };
          update-policy local;
        };
      path: /etc/bind/named.conf.local
    register: bind_zone_config
    when: domain is defined

  - name: Install BIND 🦶4--add zone file
    # re CAA record, see https://letsencrypt.org/docs/caa/
    # FIXME: support ACME-CAA - https://www.devever.net/~hl/acme-caa-live and https://news.ycombinator.com/item?id=34035148
    copy:
      content: |
        ;
        ; BIND data file for {{ domain }}
        ;
        $TTL  500
        @ IN  SOA  {{ domain }}. root.localhost. (
                    5    ; Serial
               604800    ; Refresh
                86400    ; Retry
              2419200    ; Expire
                  500 )  ; Negative Cache TTL
        ;
        @ IN  NS   {{ domain }}.
        @ IN  A    {{ ip }}
        @ IN  CAA  0 issue "letsencrypt.org"
      dest: /var/cache/bind/db.{{ domain }}
      force: false  # do not overwrite if file exists (BIND rewrites this file)
      mode: '0644'
      owner: bind
      group: bind
    register: bind_zone_file
    when: domain is defined

  - name: Install BIND 🦶5--restart
    # debugging: sudo named-checkconf  # should display nothing
    # debugging: printf "zone vxm.example.org\nupdate delete testa.vxm.example.org.\nupdate add testa.vxm.example.org. 600 IN A 9.9.9.9\nsend\n" |sudo -u bind /usr/bin/nsupdate -l  # substitute your domain; see that no errors are displayed
    # debugging: dig @127.0.0.1 testa.vxm.example.org +short  # again, substitute your domain
    systemd:
      name: bind9
      enabled: yes
      state: restarted
    when: (domain is defined) and (bind_options.changed or bind_zone_config.changed or bind_zone_file.changed)
_EOF3703_

## enable `ssh localhost` and run Ansible script
cat <<"_EOF6471_" |sudo --user $SUDO_USER bash -s -- "$domain" "$ip"
mkdir -p ~/.ssh/
if test ! -f ~/.ssh/id_ed25519; then
    ssh-keygen -q -f ~/.ssh/id_ed25519 -N '' -t ed25519
fi
if ! (grep $(cat ~/.ssh/id_ed25519.pub |awk '{print $2}') ~/.ssh/authorized_keys); then
    cat ~/.ssh/id_ed25519.pub >>~/.ssh/authorized_keys
    echo "* $(cat /etc/ssh/ssh_host_ecdsa_key.pub)" >>~/.ssh/known_hosts
fi
chmod go-w ~ ~/.ssh
chmod ugo-x,go-w ~/.ssh/authorized_keys
mkdir -p ~/hub/ && cd $_
if test "x$1" = "x"; then
  ansible-playbook -i localhost, install.yaml
else
  ansible-playbook -i localhost, install.yaml --extra-vars "domain=$1 ip=$2"
fi
_EOF6471_
