### BitBurrow configuration file
#
# Edit this file to configure the BitBurrow hub. This file is
# never modified by BitBurrow.
#
common:
  # Database file path. Can be absolute or relative to the directory of this config file.
  # Use "-" (YAML requires the quotes) for memory-only.
  db_file: data.sqlite
  log_path: /var/log/bitburrow
  # Log verbosity: 0=critical only; 1=errors; 2=warnings; 3=info; 4=debug; 5=detailed debug
  log_level: 2
httpd:
  # Domain to access hub api and for VPN client subdomains, e.g. vxm.example.org
  domain: vxm.example.org
  # Public IP address(es) to access hub api
  public_ips: []
wireguard:
  # UDP port(s) used by VPN bases; if none are defined here, one will be chosen at random
  ports: []
advanced:
  config_file_version: 5075

